FROM rocker/r-ver:4.4.3

ENV TZ America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone

ENV DEBIAN_FRONTEND noninteractive

ENV ROCKER_DATE 2025-03-19
ENV POSIT_DATE 2025-03-19

ENV R_VER 4.4.3
ENV BIOC_VER 3.20

RUN apt-get -qq update --yes && \
    apt-get install --yes tzdata \
            openmpi-bin \
            libopenmpi-dev \
            ssh > /dev/null
## Note that given difficulties running R across nodes,
## not clear it's useful to have MPI and SSH in container at this point.

## Dependencies needed for various R packages

RUN apt-get install --yes libgsl-dev \
            libglu1-mesa-dev \
            libfftw3-dev \
            coinor-libsymphony3 \
            coinor-libsymphony-dev \
            coinor-libcgl-dev \
            libzmq3-dev \
            libglpk-dev \
            libbz2-dev \
            libpcre3-dev \
            liblzma-dev \
            libicu-dev \
            libxml2-dev \
            libcurl4-openssl-dev \
            libssl-dev \
            libpng-dev \
            tcl8.6-dev tk8.6-dev \
            libnetcdf-dev \
            ed \
            libcairo2-dev \
            libudunits2-0 libudunits2-dev \
            libgdal-dev libgeos-dev \
            default-jdk default-jre \
            libmpfr-dev \
            libnode-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libjq-dev \
            cmake \
            libprotobuf-dev \
            protobuf-compiler \
            libgit2-dev \
            jags \
            coinor-symphony \
            dcraw \
            gsfonts \
            libapparmor-dev \
            libgmp3-dev \
            libprotoc-dev \
            libsecret-1-dev \
            tk-table
            
            

## Some additional packages helpful to have in container
## less is needed for help(foo) in R
RUN apt-get install --yes vim \
                          less

## Files produced by `find_packages_4.x.y.R` when that is run on a
## current installation of R.
COPY cran_packages_${R_VER}.csv /tmp/cran_packages.csv
## COPY cran_packages_update_${R_VER}.csv /tmp/cran_packages_update.csv
COPY bioc_packages_${R_VER}.csv /tmp/bioc_packages.csv


## Set up R's paths to where packages are installed.
## RUN sed -i "s/R_LIBS_USER='\/usr\/local\/lib\/R\/site-library'//" /usr/local/lib/R/etc/Renviron  # ensure that R_LIBS_USER set such that users can install packages in their home directory  # no longer needed as of rocker/r-ver:4.0.3
## (Noted previously, but doesn't seem to be correct: In R 4.3.2, not seeing an `RLIBS=` line in Renviron.site.)
RUN sed -i "s/R_LIBS=/R_LIBS_SITE=/" /usr/local/lib/R/etc/Renviron.site  # ensure that R_LIBS_USER takes precedence

## Set default repository to same snapshot as used to install packages via renv.
## https://packagemanager.posit.co/cran/__linux__/noble/2025-03-19
## Check that the repository given in `Rprofile.site` in the container is `https://p3m.dev/cran/__linux__/noble/latest` so that this `sed` invocation works.
RUN sed -i "s/p3m.dev\/cran\/__linux__\/noble/latest\//packagemanager.posit.co\/cran\/__linux__\/noble\/${POSIT_DATE}/" /usr/local/lib/R/etc/Rprofile.site

## Install CRAN packages
RUN Rscript -e "pkgs <- read.csv('/tmp/cran_packages.csv', stringsAsFactors = FALSE)[,1]; install.packages(pkgs)"

## Install Bioconductor packages
## For earlier versions of Bioconductor, do this instead of `BiocManager`:
## RUN Rscript -e "source('http://bioconductor.org/biocLite.R'); pkgs <- read.csv('/tmp/bioc_packages.csv', stringsAsFactors = FALSE)[,1]; biocLite(pkgs, suppressUpdates=TRUE, ask=FALSE)"
## Note that Bioconductor often (always?) re-installs CRAN packages on
## which Bioconductor packges depend. This is frustrating.
## For later versions of Bioconductor, do this instead of `biocLite`:
RUN Rscript -e "install.packages('BiocManager'); pkgs <- read.csv('/tmp/bioc_packages.csv', stringsAsFactors = FALSE)[,1]; BiocManager::install('BiocVersion', update=FALSE, ask=FALSE, version = \"${BIOC_VER}\"); BiocManager::install(pkgs, update=FALSE, ask=FALSE, version = \"${BIOC_VER}\")"

COPY later_packages_${R_VER}.csv /tmp/later_packages.csv

## Install CRAN packages that depend on Bioconductor packages
RUN Rscript -e "pkgs <- read.csv('/tmp/later_packages.csv', stringsAsFactors = FALSE)[,1]; install.packages(pkgs)"

## Install INLA
RUN Rscript -e "install.packages('INLA',repos=c(getOption('repos'),INLA='https://inla.r-inla-download.org/R/stable'), dep=TRUE)"

WORKDIR /workspace

## use CMD not ENTRYPOINT so can override it (e.g., for Rscript)
CMD R

## for SCF

RUN mkdir -p /scratch/users




